# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAZpGZTBDDu97rwPxvPmbaudm7U7va2v
"""

def gerar_fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]

    sequencia = [0, 1]
    while len(sequencia) < n:
        proximo = sequencia[-1] + sequencia[-2]
        sequencia.append(proximo)
    return sequencia

try:
    repeticoes = int(input("Digite o número de termos da sequência de Fibonacci: "))
    resultado = gerar_fibonacci(repeticoes)
    print(f"Sequência de Fibonacci com {repeticoes} termos:")
    print(resultado)
except ValueError:
    print("Por favor, insira um número inteiro válido.")